### ISSUE TITLE
Insteon mini remotes not working properly 

### ISSUE THREAD

**Issue by rccoleman** [shbatm/hacs-isy994#1]

**Comment by rccoleman** [comment]
I have several Insteon mini-remotes that I use isy994_control events to trigger automations. This works fine with the released PyISY and isy994 versions, but with this component and the beta PyISY I see that some of the remote buttons now show up as sensors (sensor.xxx) rather than lights (light.xxx), and most of the buttons don’t appear to have any entities associated at all. For the ones that don’t create new sensor entities, I see no events generated when I press them. I suspect that I’ll see a similar problem with my keypads based on my recollection of the last time I tried this PyISY version bit I haven’t tried them yet.

**Comment by shbatm** [comment]
I will take a look when I get a chance. I have my Mini-Remotes ignored in
Hass, so I may have broken something inadvertently and not noticed.

>

**Comment by shbatm** [comment]
Should be fixed in recent updates.
