### ISSUE TITLE
PyIsy not installing

### ISSUE THREAD

**Issue by pashdown** [shbatm/hacs-isy994#10]
‘’’
Unable to install package PyISY_beta==2.0.0.dev84: ERROR: Command errored out with exit status 1:
     command: /home/pashdown/homeassistant/bin/python3.7 /home/pashdown/homeassistant/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmp138fzsp0
         cwd: /tmp/pip-install-dvy_81nl/PyISY-beta
    Complete output (51 lines):
    fatal: not a git repository (or any parent up to mount point /)
    Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
    Traceback (most recent call last):
      File "/tmp/pip-build-env-evqxx96c/normal/lib/python3.7/site-packages/setuptools_git_version.py", line 10, in validate_version_format
        version = check_output(command.split()).decode('utf-8').strip()
      File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.7/subprocess.py", line 512, in run
        output=stdout, stderr=stderr)
    subprocess.CalledProcessError: Command '['git', 'describe', '--tags', '--long', '--dirty']' returned non-zero exit status 128.
    
‘’’

**Comment by shbatm** [comment]
I must have broke something when I pushed the latest version. I've backed off v1.0.13 until I can fix it. Please use v1.0.12

**Comment by shbatm** [comment]
Please update to v1.0.14 or remain at v1.0.12. There is an issue with the PyISY_beta release used in v1.0.13 (PyISY_beta v2.0.0.dev84)
