### ISSUE TITLE
v1.1.1 configuration error

### ISSUE THREAD

**Issue by timwing** [shbatm/hacs-isy994#14]
@shbatm, v1.1.1 just installed and I am getting this configuration error again. I did not changed my configuration.yaml, I just installed the ISY994 v1.1.1 update.

![tdw-0000](https://user-images.githubusercontent.com/60765858/76137027-48763c80-6006-11ea-8b0c-4d4a8f30dfb4.png)

![tdw-0002](https://user-images.githubusercontent.com/60765858/76137031-4d3af080-6006-11ea-9f72-d57d4d3c3b60.png)

![tdw-0001](https://user-images.githubusercontent.com/60765858/76137033-4f04b400-6006-11ea-9c37-3e7cec8d5f7d.png)

**Comment by shbatm** [comment]
Stay on the beta channel releases. You should have a v1.1.1-beta1 available.

I'm still holding off on merging the multiple ISY branch to the main release because of some changes we're working on for the PyISY module.
