### ISSUE TITLE
Renaming devices in ISY, keeping HA in sync

### ISSUE THREAD

**Issue by jonsmirl** [shbatm/hacs-isy994#15]
I had dimmers LightA(1.1) and LightB(1.2).  My device 1.2 died.  Only spare I had was a OnOff switch. Since LightB has to be a dimmer I rewired dimmer 1.1 to LightB and wired onoff 1.3 on LightA.  I then went into the ISY UI and deleted LightB, renamed LightA to LightB, named the new OnOff LightB and fixed up the groups. This all worked fine in the ISY.

HA got confused.  The new OnOff device is missing (note this device name switched from being a dimmer to an OnOff).  I also have two groups LightB, an old one switch.lightb and a new one switch.lightb_2.  There should only be one.

So how do I get the HA and ISY synced again after edits like this?

**Comment by shbatm** [comment]
The easiest way would be to delete the entities from Home Assistant, either from the Entity Registry in the Configuration tab or manually from the `config/.storage/core.entity_registry` and `core.restore_state` files. Then restart Home Assistant and let it re-register everything.

**Comment by jonsmirl** [comment]
As a future feature, is it possible to add a UI button to do the resync?

Sometimes the need for a resync could be detected automatically. For example in my case HA had to append to the name to switch.lightb_2.  Needing to append to a name would be an indication that HA and ISY are out of sync.

**Comment by shbatm** [comment]
It can be added to the list. I think it would most likely be after the config flows are implemented and requires https://github.com/automicus/PyISY/issues/69 to be implemented first.

**Comment by bkvargyas** [comment]
I have a question related to this --- I recently deleted two devices in the ISY that were synced to HA.   Restarted HA, and the devices still showed up.   Went into the Entity List in the UI, removed the two Entity's, verified they were gone, but they still showed up in devices.    Restarted HA, same result, devices are still there, related entity's are gone.  Runnning latest 1.3.6 version of your connector.    Any ideas on how to remove the devices?

**Comment by shbatm** [comment]
@jonsmirl -- Renaming will not be picked up unless you remove an entity from Home Assistant and restart or reload. That's a function of how Home Assistant manages the entities.

@bkvargyas, @jonsmirl  - As far as updating without restarted: https://github.com/shbatm/hacs-isy994/releases/tag/v1.4.1 introduces two new services that will let you reload and cleanup the integration without restarting Home Assistant.
