### ISSUE TITLE
Home Assistant looses connection to ISY after several hours

### ISSUE THREAD

**Issue by rmlinnovator** [shbatm/hacs-isy994#17]
I seem to be experiencing intermittent connectivity drops between the ISY and Home Assistant.  I am not really sure how to troubleshoot it but it happens between 12-48 hours.  If I restart Home Assistant everything comes back to life and works fine.  I don't notice anything unusual in the Home Assistant > Developer Tools > Logs.  I am still somewhat new to HA so I would appreciate any feedback.

running version 0.106.5 of HA w/ v1.1.1

**Comment by shbatm** [comment]
I'll take a look at mine and see if there is anything obvious from a recent change.

Can you please enable debug logging by adding the following in your `configuration.yaml` file?

```yaml
logger:
  default: info
  logs:
    custom_components.isy994: debug
```

You can search the logs for the following strings and see if there's a pattern or anything else showing up around that issue:

```shell
# -A and -B show ## lines before and after the line in question
grep "STRING" config_folder/home-assistant.log -A 10 -B 10
```

Search for:

- `ISY Starting Updates`
- `ISY Stopping Updates`
- `PyISY could not connect to ISY event stream`
- `PyISY lost connection to the ISY event stream`
- `PyISY reconnected to the event stream`
- `PyISY could not reconnect to the event stream`
- `PyISY attempting stream reconnect`

**Comment by rmlinnovator** [comment]
Thanks, I will turn this on now and see what I come up with.

1. v.5.0.16C
2. I am mainly using this plugin for variable support.  When it's not working I can change the variable on the ISY the corresponding HA switch doesn't update at all.  Then if I try to turn on the variable switch on the HA it will go on then immediately off.  If I reboot HA then it will work again.  Also, today when I logged back into my ISY I got the "Already Subscribed" message so I had to reboot the ISY to get things working again.

I will get the debug logging switched on.

**Comment by MechEng70** [comment]
Just FYI - I am on 5.0.16B with no issues.

**Comment by rmlinnovator** [comment]
I just checked my log and these are the last three entries and then no further ISY updates in the log since yesterday morning.

```
2020-03-15 07:49:49 INFO (Thread-932) [custom_components.isy994] ISY Request: http://X.X.X.X:80/rest/programs?subfolders=true
2020-03-15 07:49:50 DEBUG (Thread-932) [custom_components.isy994] ISY Response Recieved
2020-03-15 07:49:50 INFO (Thread-932) [custom_components.isy994] ISY Loaded/Updated Programs
```

**Comment by shbatm** [comment]
Did you make any changes to the ISY settings or variables?

Have you tried updating the custom component to v1.2.0? (this uses a different method from Hass to start and stop updates) 

I'll see if I can add some more detailed logging. You should be seeing a heartbeat log entry and if it fails for more than some period of time it's supposed to restart.

**Comment by rmlinnovator** [comment]
I don't believe I made any changes around that time.  This was the last heartbeat that I had:

`2020-03-15 07:47:44 DEBUG (Thread-3) [custom_components.isy994] ISY HEARTBEAT: 2020-03-15T07:47:44.077306`

I will update to v1.2.0.  Thanks for the quick feedback.  I'll keep an eye on it and see how v1.2.0 works.

**Comment by rmlinnovator** [comment]
Version 1.21 seems to be working better.  My ISY and HA were talking to each other reliably for about 4 days.  Yesterday I experienced another connectivity loss and things have not restored on their own.  Here was the last few lines of the log when things stopped talking to each other:

`2020-03-21 13:00:06 DEBUG (Thread-3) [custom_components.isy994] ISY HEARTBEAT: 2020-03-21TXX:XX:XX.XXXXXX
2020-03-21 13:02:11 WARNING (Thread-3) [custom_components.isy994] PyISY lost connection to the ISY event stream.
2020-03-21 13:02:11 WARNING (Thread-10573) [custom_components.isy994] PyISY attempting stream reconnect.
2020-03-21 13:02:11 INFO (Thread-10573) [custom_components.isy994] ISY Starting Updates
2020-03-21 13:02:11 WARNING (Thread-10573) [custom_components.isy994] PyISY reconnected to the event stream.
2020-03-21 13:02:11 DEBUG (Thread-10574) [custom_components.isy994] ISY Update Received:`

**Comment by shbatm** [comment]
@rmlinnovator Are you still having issues -- if so, can you please try the `master` branch in HACS? You may have to turn on `Show Beta` in the 3-dot menu on the HACS page for this integration to see the `master` option in the dropdown.
