### ISSUE TITLE
Color changing bulbs - Aeotec LED Bulb Gen6

### ISSUE THREAD

**Issue by MechEng70** [shbatm/hacs-isy994#21]
can't change the RGB code of the bulbs, either through automations or an entity panel.

**Comment by shbatm** [comment]
Support for color bulbs has been added to `pyisy` but has not been implemented on the Home Assistant end yet. I'll add it to the list.

**Comment by shbatm** [comment]
Please post the node file from `http://your-isy-ip/rest/nodes/LEDBULBADDRESS`

**Comment by MechEng70** [comment]
Here is the _1 and _186 XML files.

[ZW025_186.txt](https://github.com/shbatm/hacs-isy994/files/4332923/ZW025_186.txt)
[ZW025_1.txt](https://github.com/shbatm/hacs-isy994/files/4332924/ZW025_1.txt)

**Comment by MechEng70** [comment]
_186
GV0 - Warm white
GV1 - Cold White
GV2 - Red
GV3 - Green
GV4 - Blue

**Comment by shbatm** [comment]
One more thing:  `/rest/zwave/node/0/def/get` and `/rest/zwave/node/0/def/get` and (if it responds): `/rest/zwave/node/25/def/get`

**Comment by MechEng70** [comment]
The /rest/zwave/node/25/def/get returns 404

[get - 0.txt](https://github.com/shbatm/hacs-isy994/files/4333722/get.-.0.txt)

**Comment by MechEng70** [comment]
Think I figured out what you want.  see below.

[get ZW025_186.txt](https://github.com/shbatm/hacs-isy994/files/4333725/get.ZW025_186.txt)
[get ZW025_1.txt](https://github.com/shbatm/hacs-isy994/files/4333726/get.ZW025_1.txt)

**Comment by shbatm** [comment]
Thanks! That helps. I think I have what I need to work on the implementation. 

How does this actually show up in the ISY? Does it show up as 2 nodes, but you can only change the colors on one? The color node only looks like it accepts "ON" commands, no "OFF" commands.

Thanks again for the help. I don't use my ISY as my Z-Wave controller so I'm piecing it all together.

**Comment by MechEng70** [comment]
Shows up as two nodes.  
_1 is the on off percentage.
_186 is the color and fade up and down

See images.
![Screen Shot 2020-03-14 at 8 30 18 PM](https://user-images.githubusercontent.com/11697710/76694649-cb188080-6632-11ea-89ab-25423ba67659.png)
![Screen Shot 2020-03-14 at 8 30 31 PM](https://user-images.githubusercontent.com/11697710/76694650-cc49ad80-6632-11ea-92f2-5bc9e6f1342c.png)

**Comment by MechEng70** [comment]
The why that the color is changed from the ISY is through programs:

Color - Red Green - [ID 0017][Parent 0037][Not Enabled]

If
   - No Conditions - (To add one, press 'Schedule' or 'Condition')
 
Then
        Set 'Main / Hallway / Hallway - Color Switch' Warm White 0, Cold White 0, Red 255, Green 0, Blue 0, 
        Set 'Office / Network - Color Switch' Warm White 0, Cold White 0, Red 255, Green 0, Blue 0, 
        Set 'Master / Closet - Color Switch' Warm White 0, Cold White 0, Red 255, Green 0, Blue 0, 
 
Else
        Set 'Main / Hallway / Hallway - Color Switch' Warm White 0, Cold White 0, Red 0, Green 255, Blue 0, 
        Set 'Office / Network - Color Switch' Warm White 0, Cold White 0, Red 0, Green 255, Blue 0, 
        Set 'Master / Closet - Color Switch' Warm White 0, Cold White 0, Red 0, Green 255, Blue 0,

**Comment by shbatm** [comment]
Just a heads up, there's still no native support for controlling these devices, but in version 1.4.0, services have been added that you can used to control the devices.

Take a look at the `isy994.send_raw_node_command` service to be able to send `'DON'` with extra parameters for the color bulbs.

**Comment by shbatm** [comment]
Thinking about it more, I'm going to close this for now. Until the ISY comes up with a more cohesive way of combining Z-Wave entities into one controllable device, I'm not going to try and come up with a hacky workaround for each device type.

As mentioned above -- you should be able to use the new `isy994.send_raw_node_command` to call what you need to control the colors on the color node. See https://github.com/shbatm/PyISY/issues/17 for the command details.
