### ISSUE TITLE
Issue generating 'Thermostat' cards on versions >1.0.15

### ISSUE THREAD

**Issue by ethankrein** [shbatm/hacs-isy994#22]
When generating a new 'thermostat' card in Home Assistant with HACS ISY on a version greater than 1.0.15 the card grays out and states "Unavailable" with access to climate functions being entirely disabled.

This error should be easy to reproduce by simply deleting your exisiting thermostat card and trying to recreate it on the latest version of HACS ISY.

Error:
> Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 434, in _async_add_entity
    await entity.async_update_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 284, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 327, in _async_write_ha_state
    attr.update(self.state_attributes or {})
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 236, in state_attributes
    self.target_temperature_low,
  File "/config/custom_components/isy994/climate.py", line 173, in target_temperature_low
    self._node.aux_properties[PROP_SETPOINT_HEAT].formatted.replace("°", "")
ValueError: could not convert string to float:

**Comment by shbatm** [comment]
I'm not seeing the issue with my thermostats.

1) What firmware ISY are you runnning?
2) What type of Thermostat is it? Insteon, Z-Wave, or Zigbee?
2) Please go to `http://isy.ip.address/rest/nodes/TSTAT ADDRESS` and post the output.

**Comment by ethankrein** [comment]
> I'm not seeing the issue with my thermostats.
> 1. What firmware ISY are you runnning?

5.0.13D
> 2. What type of Thermostat is it? Insteon, Z-Wave, or Zigbee?

Insteon Thermostat Adapter 2441V
> 3. Please go to `http://isy.ip.address/rest/nodes/TSTAT ADDRESS` and post the output.

[Output](https://github.com/shbatm/hacs-isy994/files/4333089/issue.txt)

**Comment by shbatm** [comment]
Thanks! I see the issue, looks like an encoding issue from the ISY (shouldn't be a Â before the degree symbols). I'll add a workaround for it and see if that helps.

**Comment by jeffrey5059** [comment]
Running into same issue. Version 5.0.16, but my 2 are Zwave thermostats
[zwave.txt](https://github.com/shbatm/hacs-isy994/files/4333737/zwave.txt)
.

**Comment by ethankrein** [comment]
> Thanks! I see the issue, looks like an encoding issue from the ISY (shouldn't be a Â before the degree symbols). I'll add a workaround for it and see if that helps.

Thank you :)

**Comment by shbatm** [comment]
Please test v1.1.2

**Comment by jeffrey5059** [comment]
Awesome, all good now

**Comment by ethankrein** [comment]
Looks to be working for me. Thanks!
