### ISSUE TITLE
Motion sensor tamper devices have disappeared

### ISSUE THREAD

**Issue by bdraco** [shbatm/hacs-isy994#23]
The ID of one is

XX XX XX 10

I suspect the 2 digits on the end is the cause
<img width="529" alt="Screen Shot 2020-03-14 at 11 21 26 AM" src="https://user-images.githubusercontent.com/663432/76685991-fde85780-65e5-11ea-82ba-80afb7fa866d.png">

**Comment by shbatm** [comment]
Love the ISY reporting subnodes as HEX sometimes and DEC others! /s
