### ISSUE TITLE
The text is missing

### ISSUE THREAD

**Issue by MechEng70** [shbatm/hacs-isy994#32]
I just updated to the new version and the text is not showing up on the integration pop-up.  I changed the theme back to default and that doesn't help.
![Screen Shot 2020-03-16 at 2 39 53 PM](https://user-images.githubusercontent.com/11697710/76802105-34fc6b80-6794-11ea-95ae-3699cb267757.png)

Also, I had to reinstall the ISY plugin.

**Comment by MechEng70** [comment]
also, after entering the information and clicking submit, it clears the fields hangs there.

**Comment by shbatm** [comment]
> I just updated to the new version and the text is not showing up on the integration pop-up.

Please check your `config/custom_components/isy994` folder for a `.translations` folder. If that's missing the text will not show up.



> also, after entering the information and clicking submit, it clears the fields hangs there.

It's installing the most recent PyISY module when it does this. It should go through, but may take a minute.

**Comment by MechEng70** [comment]
I downloaded the en.json and created the .translation directory.  that is working now.  thanks.
