### ISSUE TITLE
Climate device no loger available

### ISSUE THREAD

**Issue by xstrex** [shbatm/hacs-isy994#36]
HACS ISY994 version: 1.2.1
HA: 107.1

My thermostat simply says n/a. More digging shows: Entity not available: climate.thermostat

I believe the relevant logs are
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 334, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/isy994/__init__.py", line 690, in device_info
    device_info["model"] += (
KeyError: 'model'
2020-03-19 11:16:52 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 334, in _async_add_entity
    device_info = entity.device_info
  File "/config/custom_components/isy994/__init__.py", line 690, in device_info
    device_info["model"] += (
KeyError: 'model'
```

I've logged into my ISY, and can query, the thermostat just fine. I've also adjusted the temperature on the thermostat, as well as the ISY so I'm fairly certain communication is working there. Coincidentally I also recently replaced the batteries in my thermostat- which I believe had nothing todo with this problem. 

Happy to provide as much details as possible. 
Cheers.

**Comment by shbatm** [comment]
Guessing you may be on ISY v4 firmware still?

Remove the `+` sign from [this line](https://github.com/shbatm/hacs-isy994/blob/eb7f4f87e1dedd803f20e21302a62ddde78ffa7c/custom_components/isy994/__init__.py#L690) in the `custom_components/isy994/__init__.py` file. 

I'll push an update when I get a chance with a real fix.

**Comment by xstrex** [comment]
Firmware on the ISY is reporting Insteon_UD994 v.4.7.5

I'll try the fix- is there a newer firmware available that I should be on?

**Comment by xstrex** [comment]
"+" removed, climate device is back (after a restart). 
Thanks, I'd consider this "fixed" but not resolved.

**Comment by shbatm** [comment]
> v4.7.5
V5.0.16C is a very stable beta (have been using v5 it for a few years now), but if you're not looking at using any of the new node server features yet, you may want to go w the 'if it ain't broke' mantra. 

One of the things V5 exposes is better categorization and naming of devices in this kind of integration. 

Anyways, as far as this error goes, I will push a true fix that will handle ISYv4 better.

**Comment by xstrex** [comment]
Thanks for the help. 
I just manually upgraded to V5.0.16C, after following their upgrade steps on the forums. Everything seems to be working great.
