### ISSUE TITLE
FanLinc Stats Disapears

### ISSUE THREAD

**Issue by wingman1487** [shbatm/hacs-isy994#39]
With update to 1.3.1 from 1.2.2, when changing fan speeds in HA the speed attribute disappears from the FanLinc entry.  However if you change the speed from an external source the speed attribute reappears with the correct status returned.

**Comment by shbatm** [comment]
Can you please provide some screenshots so I can see what you're talking about?

**Comment by wingman1487** [comment]
The first one here is what it is like before the update, the second one is after the update and a speed changes is made.  The "speed" attribute disappears when a change is made from HA, however if I change from the ISY/different App/at the wall, the "speed" attribute re-appears in HA.

![1 2 2](https://user-images.githubusercontent.com/20691788/78575660-48c64b00-77f1-11ea-9a89-434ecc3c8247.jpg)
![1 3 1](https://user-images.githubusercontent.com/20691788/78575666-4b28a500-77f1-11ea-8c8f-0aeae17ecceb.jpg)
