### ISSUE TITLE
hacs-isy994 v1.3.5 - ISY Could not parse response

### ISSUE THREAD

**Issue by timwing** [shbatm/hacs-isy994#44]
@shbatm just did a clean install of hacs-isy994 v1.3.5. Configured 2 ISY994's and this is the only error.

`2020-04-12 22:41:40 ERROR (SyncWorker_11) [custom_components.isy994] ISY Could not parse response, poorly formatted XML.: NetworkResources`

**Comment by shbatm** [comment]
Theres an issue with what the ISY is providing for the Network Resources. Can you send `/rest/networking/resources` from whichever of the ISYs is throwing the error?

**Comment by timwing** [comment]
@shbatm Found the issue...I had a "&" in one of the network resource names :( Fixed that and no more errors.

Thank you for your help!
