### ISSUE TITLE
Duplicate Devices but Single Entities

### ISSUE THREAD

**Issue by wingman1487** [shbatm/hacs-isy994#45]
Thanks for all your awesome work and support, hope the things I continue to find are useful and help improve the functionality of your module! 

Unfortunately I'm not really sure when this started happening, but today I noticed that there are duplicate entries for somethings in the Devices area where there are only single entries in the Entities area.  Attached there are 2 Down Hall Lights and 2 Downstairs Thermostats.  Each of these Devices seems to have a unique identifier as one of the Down Hall Lights was set in the past to have the Foyer Area where the supposed duplicate has no Area.  This would cause issues when trying to create automation against a Device.

![image](https://user-images.githubusercontent.com/20691788/79130429-918b8000-7d6c-11ea-9eec-85206a75a0a9.png)
![image](https://user-images.githubusercontent.com/20691788/79130444-97816100-7d6c-11ea-8c1b-ada7d90754fb.png)

**Comment by shbatm** [comment]
Ah, there was a change in how the identifier string is created (no longer strips out the colons and underscores). Sorry about that. The easiest thing to do would be to stop HA, and delete the `config_dir/.storage/core.device_registry` file and then restart.

**Comment by shbatm** [comment]
Updated the 1.3.5 notes with a Breaking Change warning.

**Comment by wingman1487** [comment]
That was it, thanks for the info!
