### ISSUE TITLE
Duplicate devices

### ISSUE THREAD

**Issue by julianhoare** [shbatm/hacs-isy994#48]
Sometime in the last week, my ISY994 integration seems to have created duplicate devices.  Entities are not duplicated and there are exactly two devices per entity. Only one device seems to be actually associated with its corresponding entity in the UI, however.

Looking in core.device_registry, I can indeed see two of each device.  The only difference seems to be that the MAC for the ISY is colon-separated in one and not the other.

"identifiers": [
[
"isy994",
"0021b901XXYY_F F1 ZZ 1"
]

vs

"identifiers": [
[
"isy994",
"00:21:b9:01:XX:YY_F F1 ZZ 1"
]

Is there a way to automatically clean this up, or should I just remove the duplicate entries?  If so, which is correct - colon-separated or not?  Thanks.

**Comment by shbatm** [comment]
Please see the release notes for the recent changes:

https://github.com/shbatm/hacs-isy994/releases/tag/v1.3.5

**Comment by MechEng70** [comment]
I did delete the files as mentioned in the release notes and restarted.  Still have the duplicate devices.

**Comment by shbatm** [comment]
You'll have to delete them while HASS is not running, otherwise it just saves a new copy as soon as there's a change. The correct ones should now be the ones with the colons.

Sorry for the inconvenience, I messed it up the first time and there's no easy way to clean it up programatically.

**Comment by MechEng70** [comment]
Thanks!  Found it and all is well.

**Comment by shbatm** [comment]
It doesn't solve it all, but if you upgrade to 1.4.1, you can run the `isy994.cleanup` service to delete a lot of the extra entities that may have cropped up over the last several updates--won't solve this issue though.
