### ISSUE TITLE
Insteon device with leading 0 (e.g 0D.34.67) dropped off. 

### ISSUE THREAD

**Issue by sbigras** [shbatm/hacs-isy994#49]
Hi, 

running HACS-isy994 version 1.3.6. When adding the isy integration, it seems that the insteon device with an address start with a "0" are added, but without the first digit (the 0). 

![Screenshot from 2020-04-22 16-19-31](https://user-images.githubusercontent.com/16723934/80030625-75978500-84b6-11ea-979f-a95d61b5bab7.png)

thank you for your work

**Comment by shbatm** [comment]
Are all the controls working? I can look into it more if not, but if I recall correctly, the ISY drops the leading 0s for each 2-digit subset. If everything still works, it shouldn't be an issue.

**Comment by sbigras** [comment]
All the ones without a leading 0 Insteon address do not work. I have three
insteon devices with leading 0, and all of them are not working. Looking
closer to the logs, I noticed that one of the devices that does start with
a 0, give an error in HASS with the address of another one completely
different. For instance, one device (pool_shed) that has an insteon address
0B.AE.0A, when turning it on via HASS) gives me the following errors, with
totally unrelated insteon address:

2020-04-23 07:40:35 WARNING (SyncWorker_6) [custom_components.isy994] Bad
ISY Request: http://192.168.3.9:80/rest/nodes/18%204D%207B%203/cmd/DON 404:
retry #0
2020-04-23 07:40:35 WARNING (SyncWorker_3)
[pywemo.ouimeaux_device.api.service] Error communicating with WeMo Insight,
retry 2
2020-04-23 07:40:36 WARNING (SyncWorker_6) [custom_components.isy994] Bad
ISY Request: http://192.168.3.9:80/rest/nodes/18%204D%207B%203/cmd/DON 404:
retry #1
2020-04-23 07:40:37 WARNING (SyncWorker_6) [custom_components.isy994] Bad
ISY Request: http://192.168.3.9:80/rest/nodes/18%204D%207B%203/cmd/DON 404:
retry #2
2020-04-23 07:40:38 WARNImy core.entity.registry and NG (SyncWorker_6)
[custom_components.isy994] Bad ISY Request:
http://192.168.3.9:80/rest/nodes/18%204D%207B%203/cmd/DON 404: retry #3
2020-04-23 07:40:42 WARNING (SyncWorker_6) [custom_components.isy994] Bad
ISY Request: http://192.168.3.9:80/rest/nodes/18%204D%207B%203/cmd/DON 404:
retry #4
2020-04-23 07:40:43 WARNING (SyncWorker_6) [custom_components.isy994] Bad
ISY Request: http://192.168.3.9:80/rest/nodes/18%204D%207B%203/cmd/DON 404:
retry #5
2020-04-23 07:40:43 ERROR (SyncWorker_6) [custom_components.isy994] Bad ISY
Request: http://192.168.3.9:80/rest/nodes/18%204D%207B%203/cmd/DON 404:
Failed after 5 retries
2020-04-23 07:40:43 WARNING (SyncWorker_6) [custom_components.isy994] ISY
could not send on command to 18 4D 7B 3.

I can turn it on fine with the ISY console.I have not tested the other two
devices with leading 0 insteon addresses.

I checked the devices in the ISY integration, and it has the proper insteon
ID (minus the leading 0) address
[image: image.png]
I hope this helps.

and again thank you for the module and help, I really appreciate them.

**Comment by shbatm** [comment]
Interesting. I'm not sure where it's pulling that other address from at all... A few questions:

1) Do the devices with no leading zeros work if you control them directly from a web browser using REST without the zeros (per ISY, the calls shouldn't have the zeros):
    - e.g. does http://192.168.3.9:80/rest/nodes/D%20AC%2046%201/cmd/DON turn on your Pool_Light? (%20 is just an encoded space `" "`, you can type the spaces directly in the browser to try too).
    - if it doesn't can you please post any error you get in the browser?
2) Do you have a device with address `18 4D 7B`? If so, is it a KeypadLinc or RemoteLinc by any chance? 
    - If it is a KeypadLinc / RemoteLinc, make sure you weren't mixing up entities in Home Assistant and trying to control that device instead (easy to mess up, trust me, I've done it multiple times).
    - If you don't have that address then very strange, and I'll need to dig further.

**Comment by sbigras** [comment]
Hi

response to question 1: the ISY returns a http 200 when using the following
URL http://192.168.3.9/rest/nodes/D%20AC%2046%201/cmd/DON and the light
come on and off with DOF.
<http://192.168.3.9/rest/nodes/B%20AE%20A%201/cmd/DOF>

Also tried it on another device which started with 0B.AE.0A - also got a
200 with this URL http://192.168.3.9/rest/nodes/B%20AE%20A%201/cmd/DON -
notice that both bytes starting with 0, the leading zero was removed.

So it looks like its behaving the way it should.

Question 2:

Yes 18 4D 7B does exist and is assigned to a 6 button keypad. the pool Shed
light is assigned to a secondary button and the keypad switch. I did find a
new "pool Shed Light 2" which came from the ISY integration import.

Now I'm doubting if the Pool Shed light was properly mapped before I
re-imported by Insteon devices via the HACS-ISY integration module.

I believe all is good, and that there was actually no issue with the code,
only operator error, me.

Sorry for the disturbance and thank you for walking me through it.

Cheer

**Comment by shbatm** [comment]
Not a problem. Like I said above, I've done the same thing. Especially if they're named the same. A recent change made to PyISY exposed a lot of keypadlinc and remotelinc buttons that previously didn't show up in Hass (if they were grouped in the ISY admin console) so no worries. Glad it's working. Reopen if you find an issue.
