### ISSUE TITLE
Turning lights on with brightness=100% doesn't work when lights have Local On Level

### ISSUE THREAD

**Issue by wkonkel** [shbatm/hacs-isy994#5]
# Problem
Within ISY994 console, I have configured a light to have an `On Level (Applied Locally)` of 50% (127). In Home Assistant, if I issue a service call for `light.turn_on` with service data of `entity_id: light.kitchen_light` and `brightness: 255` the light turns on to 50% (On Level). This is incorrect behavior and the light should turn on to full brightness.

# Solution
After some testing and watching "Event Viewer" in ISY994, it looks like there is some special behavior within HASS for brightness levels 255 vs. 254. Specifically, `light.turn_on` with:
* `brightness: 255` - light turns on to 127 (NOT expected, this is the OnLevel bug)
* `brightness: 254` - light turns on to 255 (NOT expected)
* `brightness: 253` - light turns on to 253 (expected)

I modified light.py to take advantage of this special treatment of 255 vs. 254 and the bug goes away. Here is the diff:
```
    def turn_on(self, brightness=None, **kwargs) -> None:
        """Send the turn on command to the ISY994 light device."""
+       if brightness==255:
+           brightness=254
        if not self._node.on(val=brightness):
            _LOGGER.debug("Unable to turn on light")
```

**Comment by shbatm** [comment]
This should be fixed in the latest version of PyISY_beta (the underlying module for this component). If `brightness=255` was sent, it was ignored and "on" was called with no brightness. This has been changed to accommodate Insteon On Levels.
