### ISSUE TITLE
Documentation on new services

### ISSUE THREAD

**Issue by bkvargyas** [shbatm/hacs-isy994#58]
Great work guys on the move to integration within HA!   Looks like lots of hard work!    I have a question, being somewhat new to HA.   The isy99.reload and system_cleanup commands, those are pretty easy to figure out how to use the developer tools section and call those commands.   However, things like set on levels, calling programs, etc I have no clue how to make these services work.

Also, with the new Fast On/Fast Off, How would you go about using that to execute an automation --- example:

![image](https://user-images.githubusercontent.com/8314737/81029414-7206e500-8e4a-11ea-8797-d3feffafdff4.png)

This is any ISY Program --- I'd like to duplicate this automation in HA or Node Red.  

Brian

**Comment by shbatm** [comment]
I'll post a more complete answer later when I'm at a computer, and documentation will be updated later this week, but in general, I find the best way to figure out services in HA:

1) Open Developer Tools from your sidebar 
2) Find the service you want in the drop down list. 
3) An explanation of the service and example data should show up below.
