### ISSUE TITLE
Does v1.5 support HA 109.6?

### ISSUE THREAD

**Issue by rccoleman** [shbatm/hacs-isy994#65]
I'm hesitant to file an issue that should be resolved by using the built-in integration in 0.110.0, but I saw some early failures when I tried to install v1.5.0 on my mainline 0.109.6 install and the isy994 component failed to load.  The custom component started working again when I reverted to v1.4.3.

Unfortunately, I don't have the failure log any more because I reverted the addon version and it booted successfully.  It appeared to be related to these changes because I recall it complaining about `LockEntity`.

```
- Rename BinarySensorDevice to BinarySensorEntity (home-assistant/core#34462)
- Rename LockDevice to LockEntity (home-assistant/core#34594)
- Rename SwitchDevice to SwitchEntity (home-assistant/core#34673)
- Rename LockDevice to LockEntity (home-assistant/core#34594)
- Rename CoverDevice to CoverEntity (home-assistant/core#34595)
- Rename Light to LightEntity (home-assistant/core#34593)
- Rename ClimateDevice to ClimateEntity (home-assistant/core#34591)
```

LIke I said, maybe not worth addressing if everything works together in 0.110.0 without the need for this custom component, but I worry about folks who see the v1.5.0 update and just hit "go".  I can go back to v1.5.0 and capture the actual failure logs if necessary.

**Comment by shbatm** [comment]
Apologies, I need to bump the minimum version...

This is a change made in 0.110.0

**Comment by rccoleman** [comment]
No worries, thanks for the quick response.
