### ISSUE TITLE
Node Red Call service not working.

### ISSUE THREAD

**Issue by MechEng70** [shbatm/hacs-isy994#68]
I am attempting to arm and disarm based on occupancy.  

The challenge is that the call service in node-red is giving an API error.  

![Screen Shot 2020-06-16 at 9 26 57 PM](https://user-images.githubusercontent.com/11697710/84855316-aa3c3e80-b018-11ea-882f-edd311d48061.png)

If the service is called from the Developer Services, it works.  What I am missing?

![Screen Shot 2020-06-16 at 9 27 30 PM](https://user-images.githubusercontent.com/11697710/84855314-a9a3a800-b018-11ea-853d-f5022207f3ea.png)

**Comment by shbatm** [comment]
Are you sure you posted this in the correct spot?

**Comment by shbatm** [comment]
But anyways --- you need brackets and quotes in your Node-RED JSON field:

```json
{ "mode": "armed }
```

**Comment by MechEng70** [comment]
I thought I was because it isn't working with the Arlo service.

The brackets and quotes fixed the may data.  However there is an error to call-service API.  I will have to contact someone else.  Thanks.

**Comment by MechEng70** [comment]
you are right, I am in the wrong spot.  my bad... but I did figure it out... been a long day.
