### ISSUE TITLE
Call Service - parameters

### ISSUE THREAD

**Issue by MechEng70** [shbatm/hacs-isy994#69]
Attempting to change the color of an RGB light with the GV parameters.  The light.reading_light works with the command DON but when the parameters line is added there is an error:
Here is the light and sensor from the developer system setup:

![Screen Shot 2020-06-18 at 8 36 28 PM](https://user-images.githubusercontent.com/11697710/85094532-d801be80-b1a3-11ea-8989-c4272a85b3b9.png)
![Screen Shot 2020-06-18 at 8 36 14 PM](https://user-images.githubusercontent.com/11697710/85094533-d89a5500-b1a3-11ea-9c99-9c4baea1d347.png)

Here is the error in Node Red when attempting to run the parameters.  
Node Red Data section:
```
{
    "command": "DON",
    "parameters": "[GV2 255, GV3 250, GV4 250]"
}
```

Error from Node red:
`"Call-service API error.  Error Message: expected a dictionary for dictionary value @ data['parameters']"`

Not sure if these are related.  I can get the light to turn on and off, but not interact with the RGB colors.

**Comment by MechEng70** [comment]
I finally figured this out... can you update the template in the services.  This is what will change the RGB bulbs:

`parameters: {"GV2":"255", "GV3":"200", "GV4":"200"}`

This works in Node-Red.

**Comment by shbatm** [comment]
I have something similar in the example but I just noticed it's not appearing correctly in the Services page so I'll get that updated. Glad you got it working.

**Comment by MechEng70** [comment]
I saw that too when I was looking through the code section after I "figured it out".  It does seem to require the "" around the values.
