### ISSUE TITLE
it's not working when installing with HACS using v1.09

### ISSUE THREAD

**Issue by askesian** [shbatm/hacs-isy994#7]
I've installed this via HACS, and I've added (already had) the isy config values. When I restart HA, it takes forever to restart, and once it finally does, it says that there's something wrong with the isy994 configuration, but there is for sure nothing wrong with it. Could this be related to the version of PyISY (I see the requirements are 2.0.0.8 or something like that)?

**Comment by shbatm** [comment]
Please post your config section.

**Comment by askesian** [comment]
isy994:
  host: !secret isy_host
  username: !secret isy_user
  password: !secret isy_password

Of note - I found this, which describes the problem I'm experiencing (although the linked site/page indicates that you've already resolved this) - https://www.gitmemory.com/issue/home-assistant/home-assistant/23329/485956976
