### ISSUE TITLE
Z-Wave Motion Sensor (AeoTec Multi-Sensor 6) changed from binary_sensor to switch

### ISSUE THREAD

**Issue by derekatkins** [shbatm/hacs-isy994#72]
Hi,

I just upgraded from 0.114.4 with the built-in isy994 integration to the 0.115beta with hacs-isy994 today.  I have several AeoTec MultiSensor6 devices on my network, connected through the ISY.  I noticed that when I converted, the motion sensors changed from a binary_sensor to a switch within HA!

So where I used to have `binary_sensor.zw_003_motion_sensor_1` which had a nice 'person' icon next to it and a device_class of 'motion', I now have `switch.zw_003_motion_sensor_1` with the ugly lightning-bolt icon.

Was this an intentional change or is it a bug?  It seems strange to have a motion sensor categorized as a switch to me.  It's not like I can change its value remotely!

**Comment by derekatkins** [comment]
Oh, and a similar thing happened to the "Binary Sensor" node -- it's now reported as a switch instead of a binary_sensor.

**Comment by shbatm** [comment]
No, it was not an intentional change.

I'll take a look at the Nodes file you sent and see what happened.

**Comment by shbatm** [comment]
Looks like something is causing [`_check_for_zwave_cat`](https://github.com/shbatm/hacs-isy994/blob/a493bb495edeef69caddabc9b53768da6a7c79eb/custom_components/isy994/helpers.py#L148), which sorts z-wave devices, to fail and it's falling back to categorization by unit of measurement, which drops them in as switches (UOM 78). I'll investigate further today.

**Comment by derekatkins** [comment]
FTR, upgraded from b11 to b12 today and still have the issue.  However I have removed myself from the beta stream for now.

**Comment by shbatm** [comment]
This is actually an issue with PyISY (automicus/PyISY#128) and will be resolved in the next dev version of PyISY.

**Comment by shbatm** [comment]
@derekatkins seeing as you have a large ISY network, if you would still be willing to do some testing on the beta branch with the HACS version installed (or even if you just want to use the HACS version after 0.115.x) I would appreciate any feedback you could give on the performance of the HACS model. It *should* be quicker in most regards when communicating from HA to ISY.

**Comment by derekatkins** [comment]
@shbatm Absolutely!  I've got 0.115.0b12 now but I've switched back to non-beta, so I'll upgrade to 0.115.1 once it's out.  However, I've still got the 3.x isy994 component and will happily test further, when you ask me to upgrade.  I've got it manually installed from a git clone, so just let me know when to pull and install and I can do so.

**Comment by shbatm** [comment]
Awesome, thanks!

You should be clear to test whenever you wish after HA 0.115.0 is released. The hacs-isy994 version should now have the fixes for this incorporated into v3.0.0dev14, and the async connector has been pretty stable for a while (see automicus/PyISY#107), just trying to flush out any bugs (like this one) before upgrading the core.

**Comment by shbatm** [comment]
Also, please see #74 when you have a chance. I noticed that your sirens were sorting by an old method and would like to add the full support for them

**Comment by derekatkins** [comment]
> Also, please see #74 when you have a chance. I noticed that your sirens were sorting by an old method and would like to add the full support for them

I'll pull the current code and test it today, and I'll check out #74 as well.  I don't connect to my sirens directly from HA, I have scenes in the ISY that I use to get all my sirens to go off at once.

**Comment by derekatkins** [comment]
Quick question: Do I need to restart all of HA to take this update, or can I just reload the integration?

**Comment by shbatm** [comment]
Full restart. It will need to load the new dependency.

**Comment by derekatkins** [comment]
Thanks.  Restarted.  I'll check it out shortly.

**Comment by shbatm** [comment]
That's what the `isy994.cleanup_entities` service is for.

**Comment by derekatkins** [comment]
Eh, I just did it by hand.  It was easy enough to list the entities, sort by status, select the 20-ish items, and click "remove".  :-D

**Comment by derekatkins** [comment]
> Awesome, thanks!
> 
> You should be clear to test whenever you wish after HA 0.115.0 is released. The hacs-isy994 version should now have the fixes for this incorporated into v3.0.0dev14, and the async connector has been pretty stable for a while (see [automicus/PyISY#107](https://github.com/automicus/PyISY/issues/107)), just trying to flush out any bugs (like this one) before upgrading the core.

Just responded over there.
I think this bug can be considered "fixed" as of today.
