### ISSUE TITLE
Add support for ISY device renaming from within HA

### ISSUE THREAD

**Issue by bkvargyas** [shbatm/hacs-isy994#75]
The new firmware 5.2.0 (RC3) now supports the following in REST ---

0000763: Add REST API that allows you to rename a node ( /rest/nodes/<nodeAddress>/change?name=<newName> )

See here:
https://forum.universal-devices.com/topic/30539-release-520-rc3-is-now-available/

This would be great when renaming nodes within HA if they are also renamed within the ISY as well...

**Comment by shbatm** [comment]
@bkvargyas this is now available in the beta version `3.0.0.dev18`.
