### ISSUE TITLE
Zwave brightness control

### ISSUE THREAD

**Issue by Mandaur1** [shbatm/hacs-isy994#76]
Just for openers big thank you for an excellent core integration of the isy. I have the isy and HomeKit integration working great. The problem I’m trying to figure out is how to communicate with dimming lights using 0-100 parameters vs 0-255. This may not be the place to ask the question and if that’s the case I apologize. If someone could point me in the right direction or help me with this I would very much appreciated. Im new to HA and I’m not big on programming but I can figure things out with a little help. There are several references using a template but I was not able to get that to work.

**Comment by shbatm** [comment]
@Mandaur1 can you provide some example of what/where you're trying to do? Where exactly are you converting between the 0-255 and 0-100 scales?

**Comment by Mandaur1** [comment]
I have the ISY hub with all zwave devices : bulbs, dimmers, etc. If I want to control a dimmer switch, HA sends a signal to ISY 0-255. Isy receives it as a a percent so if I set HA to 100 which is 39%, ISY is at 100% brightness. Maybe I’m doing something wrong and there is an easier way around this. I have had sometime to think about this and this is what I came up with so far. 
  - platform: template
    lights:
      gold_lamp:
        friendly_name: "Gold Lamp"
        value_template: >-
          {% if states.light.gold_lamp_isy.attributes.brightness %}
            on
          {% else %}
            off
          {% endif %}
        turn_on:
          service: light.turn_on
          entity_id: light.gold_lamp_isy
        turn_off:
          service: light.turn_off
          entity_id: light.gold_lamp_isy
        set_level:
          service: light.turn_on
          data_template:
            entity_id: light.gold_lamp_isy
            brightness: "{{ ((brightness) | int / 2.55) | round(0) }}"

This seems to be working ok except for when I restart HA and dimmers show 100% even though they are not. I’m sure I need to add level template. I’m still trying to learn. I hide the original entity. This also translates well into HomeKit. Hope I’m making sense.

**Comment by shbatm** [comment]
Use a web browser and send me the results of http://your-isy-address/rest/nodes/ZWxxxyyy where ZWxxxyyy is whatever the ISY reports as the address for those dimmers. I'll see if there's something I can implement upstream and prevent you from needing the template.

**Comment by Mandaur1** [comment]
@shbatm hello. I sent you the results through the udi forum.

**Comment by shbatm** [comment]
Updating based on conversations in the UDI Forum: This is an issue with the way the ISY handles Z-Wave brightness parameters; it uses a different unit of measurement which works on the 0-100 range instead of the 0-255 range.

Related Home Assistant Community thread from 2018-2019: https://community.home-assistant.io/t/brightness-0-100-not-255/77107/20

I will open an issue on PyISY for this resolution.

**Comment by shbatm** [comment]
Closed via home-assistant/core#42915.
