### ISSUE TITLE
All Keypad Buttons Show as Sensors

### ISSUE THREAD

**Issue by wingman1487** [shbatm/hacs-isy994#77]
I have a bunch of KeypadLincs that I use to control my FanLincs, I just noticed that all of the buttons on them went from the "switch" class to the "sensor" class.  The one entry that didn't change was the On/Off button that is the main switch for that device, it shows up as class "light", was this intended?

![image](https://user-images.githubusercontent.com/20691788/93831648-eb0bab00-fc38-11ea-9603-9fdabb9672c3.png)

![image](https://user-images.githubusercontent.com/20691788/93831735-260dde80-fc39-11ea-8889-bdfe06321777.png)

**Comment by shbatm** [comment]
Yes, it was [intentional](https://github.com/home-assistant/core/pull/35391). 

> Both KeypadLinc Secondary Buttons and RemoteLinc2 Buttons have been moved from switch to sensor. This is because these buttons cannot actually be directly controlled via commands sent from the switch platform, doing so results in communication errors from the ISY because the commands are not valid. These devices are being moved to sensor instead of binary_sensor because they report a state in a range from 0 to 255; 0=Off, 255=On` according to their last brightness/dimming level sent.

**Comment by wingman1487** [comment]
Awesome, getting back into testing and I just noticed, thanks!
