### ISSUE TITLE
 light domain lighting is not consistent #32073 

### ISSUE THREAD

**Issue by pashdown** [shbatm/hacs-isy994#8]
I should have opened this bug here.

https://github.com/home-assistant/home-assistant-polymer/issues/4956#issue-569120188

**Comment by shbatm** [comment]
@pashdown Please update to v1.0.12 in HACS and see if that fixes the issue. Appears to have resolved the errors I was getting on my end.

**Comment by pashdown** [comment]
Woot!  Fixed!
