### ISSUE TITLE
Ignore state of wireless controllers when determining group (scene) state

### ISSUE THREAD

**Issue by MrBill12** [shbatm/hacs-isy994#80]
Wireless controllers are one direction devices that do not wake-up and accept state changes when another controller changes the state of a group.  Wireless controllers do not have a local state display, they simply report events.

The unexpected behavior is that groups can remain in the 'on' state when the group is effectively off.   The desired behavior is to better reflect the real-world state of the group by ignoring the state of wireless devices.

Devices to consider include: Mini remote, open/close sensor, hidden door sensor, motion sensor, etc based on NodeDefId.  (I looked for a list of NodeDefId's to attempt to better define, I didn't locate anything current however)

(Note: at least one other popular/formerly popular 3rd party client seems to treat wireless remotes in the manner described here.)

**Comment by shbatm** [comment]
Moved to automicus/PyISY#153
