### ISSUE TITLE
Suggested area support

### ISSUE THREAD

**Issue by bdraco** [shbatm/hacs-isy994#82]
Is the `location` field used enough that it would make sense to load it into `device_info` as `suggested_area`?  We could slowly gather the `/notes` over time once the integration is up and running and set the `suggested_area`

Example: https://github.com/home-assistant/core/pull/45941

https://wiki.universal-devices.com/index.php?title=ISY_Developers:API:REST_Interface#Properties

```
/rest/nodes/<node>/notes
Returns the notes for the node
Schema (Notes):

<NodeProperties>
  <location>Free form text</location>
  <description>Free form text</description>
  <isLoad></isLoad>
  <spoken>The spoken name</spoken>
</NodeProperties>
```

**Comment by shbatm** [comment]
I used it on my old house, but not for the new house.

All of my devices are grouped into ISY folders for each different "area", maybe we could use the folder for suggested areas? Or add a config option to do so?

**Comment by bdraco** [comment]
So that sounds like a much better idea.... and conveniently will probably just work for most people.  Since its only suggested and it won't override their area choice I don't think it needs to be can option.

<img width="345" alt="Screen Shot 2021-02-21 at 12 34 07 PM" src="https://user-images.githubusercontent.com/663432/108641386-10e4e800-7443-11eb-9bf8-7cf260b26a3a.png">

**Comment by shbatm** [comment]
You should be able to grab the folder name from the path [here](https://github.com/home-assistant/core/blob/50a07f6d25ab40a1e3d435a885029839e56364a7/homeassistant/components/isy994/helpers.py#L281) during sorting. I don't think you can rely on `node.parent_node` later, but I can't remember for sure.
